name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.1

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1.171.0
      with:
        ruby-version: 3.0

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Run RuboCop
      run: bundle exec rubocop

    - name: Start Redis
      run: docker ps -a

    - name: Run RSpec tests
      env:
        REDIS_URL: redis://localhost:6379
      run: bundle exec rspec
